### ISSUE TITLE
Cannot add items to Or / And filters in 1.18.1

### ISSUE THREAD

**Issue by LegendaryTot** [LatvianModder/Item-Filters#13]
Latest version of the mod in 1.18.1 does not allow adding items to the Or / And filters. I tested the 1.16.5 version and am able to add items to the filter (right click + click items onto the GUI). In 1.18.1 it does not work, I tried lots of different ways and they seem broken.

**Comment by AdamEternal** [comment]
For me, it's all filters that require moving an item from the inventory into a filter slot. All text-based and selection-based filters seem to work fine.

Tested on:
- Minecraft 1.18.1
- Forge 39.0.55
- Item Filters 1801.2.6-build.16

**Comment by Elrol** [comment]
I am also having this issue. I am using Forge 39.1.2 for 1.18.1 along with the same mod version.

**Comment by itsdinkd** [comment]
Same. 
![image](https://user-images.githubusercontent.com/35115304/166120266-70b83292-9b6e-40c5-ac18-ce58b9164e8c.png)
cannot move anything up

**Comment by ZoMadeStuff** [comment]
Had the same issue in 1.18.2. latest mod version. Forge 40.1.0

**Comment by BillBodkin** [comment]
Fabric 1.18.2 has same issue

**Comment by HockeyZman2000** [comment]
Can report having the same issue on Forge 40.1.20. Cannot put other filters in the AND / OR filters either along with items

**Comment by TheButterbrotMan** [comment]
I can report having the same issue on Fabric 0.14.6 in Version 1.18.2.

**Comment by TheButterbrotMan** [comment]
Is there any workaround?

**Comment by sleepingdragoninn** [comment]
Same issue in Quilt 0.16.1 (juuust in case anyone was wondering if it was a QSL breakage - it's not!)

**Comment by freerig** [comment]
Same Isue in 1.18.2 forge server

**Comment by itsdinkd** [comment]
> Is there any workaround?

You have to build a manual nbt while selecting the OR filter item in ftb quests. I'm on vacation now so I cannot provide the nbt but you can download my pack to view my quest that uses it. Another Quality modpack 2, check the starting_out.snbt file in ftbquests folder, look for gobber nbt
