### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by gabgat** [LatvianModder/Item-Filters#20]
I have translated the mod to italian, i'll send you the file in .txt because github does not support .json in this field...
Can you update the mod? We need Italian for a modpack. Thank you!
[it_it.txt](https://github.com/LatvianModder/Item-Filters/files/8577570/it_it.txt)

**Comment by Zekromaster** [comment]
Why sending a literal file in the issues? Just open a Pull Request.

**Comment by MaxNeedsSnacks** [comment]
Thanks for the PR, just merged it into 1.18 and it should be out with the next release
