### ISSUE TITLE
Fabric 1902 version improperly tagged on either cf or fmj

### ISSUE THREAD

**Issue by sleepingdragoninn** [LatvianModder/Item-Filters#26]
![image](https://user-images.githubusercontent.com/55819817/189468578-e68fa29e-3c76-449b-bcd7-e054c6e6e4e7.png)

![image](https://user-images.githubusercontent.com/55819817/189468564-d8aa938e-1e81-4ca5-bb49-3ed0baaa00e5.png)

Please also yank this version if a new 1.18.2 version isn't going to be uploaded, otherwise it will permanently cause issues with mod updaters.

**Comment by remplerus** [comment]
not only fabric is affected, this is also on forge's mod

**Comment by MaxNeedsSnacks** [comment]
*sigh* I don't have access to the CF project, so I'll have to wait for lat to fix this for the current version, but all new versions should now properly be tagged

**Comment by MaxNeedsSnacks** [comment]
Fixed on CurseForge now
