### ISSUE TITLE
Mod tagged with wrong MC Version on Curseforge (1902.2.9-build.35)

### ISSUE THREAD

**Issue by Ludi87** [LatvianModder/Item-Filters#27]
**Version**:  1902.2.9 - build 35

![image](https://user-images.githubusercontent.com/13112051/189520020-2b6f1940-e233-423d-ac2e-d02e68aa3f6c.png)

![image](https://user-images.githubusercontent.com/13112051/189520055-f4df778f-8672-4b67-940a-00d9e99c4f28.png)

**Comment by MaxNeedsSnacks** [comment]
Duplicate of #26
