### ISSUE TITLE
[FTB] Mods require Item Filter mod 1.20.1 

### ISSUE THREAD

**Issue by conetopia** [LatvianModder/Item-Filters#39]
New modpack won't launch because everything is on Mc 1.20.1
But the itemfilters mod isn't even on 1.20.0 yet, and really need it for 1.20.1

**Comment by samuelh2005** [comment]
In the mean time, you could use `git `to download the code on the `1.20/dev` branch and compile it yourself.

**Comment by MaxNeedsSnacks** [comment]
Ugh I forgot to merge to a main branch
sec lmao

**Comment by MaxNeedsSnacks** [comment]
Aaaaand done, should be out on CurseForge in a couple mins
